# Generated by Django 5.2.12 on 2026-04-06 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Mã Thiết Bị')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('status', models.CharField(choices=[('ready', 'Sẵn sàng'), ('borrowed', 'Đang mượn'), ('maintenance', 'Đang bảo trì'), ('lost', 'Thất lạc/Hỏng')], default='ready', max_length=20, verbose_name='Trạng thái')),
                ('purchase_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ngày mua')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': '1. Kho Thiết bị Smart Lab',
            },
        ),
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mượn')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian trả')),
                ('status', models.CharField(choices=[('borrowed', 'Đang mượn'), ('returned', 'Đã trả')], default='borrowed', max_length=20, verbose_name='Trạng thái phiếu')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú tình trạng')),
                ('borrower', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên mượn')),
                ('for_class', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.RESTRICT, to='academic.class', verbose_name='Sử dụng cho Lớp')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.device', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Phiếu mượn trả',
                'verbose_name_plural': '2. Lịch sử Mượn/Trả',
            },
        ),
    ]
