# Generated by Django 5.2.12 on 2026-04-06 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khóa học')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khóa học')),
                ('grade_group', models.CharField(choices=[('mam_non', 'Mầm non (Dưới 6 tuổi)'), ('1-3', 'Khối Lớp 1-3 (6-8 tuổi)'), ('4-6', 'Khối Lớp 4-6 (9-11 tuổi)'), ('7-9', 'Khối Lớp 7-9 (12-14 tuổi)'), ('10-12', 'Khối Lớp 10-12 (15-18 tuổi)'), ('all', 'Mọi lứa tuổi (Không giới hạn)')], default='all', max_length=20, verbose_name='Độ tuổi phù hợp')),
                ('total_modules', models.IntegerField(default=12, verbose_name='Tổng số Học phần')),
                ('sessions_per_module', models.IntegerField(default=12, verbose_name='Số buổi / Học phần')),
                ('price_per_module', models.IntegerField(default=5000000, verbose_name='Học phí / Học phần (VNĐ)')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': '1. Danh mục Khóa học',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Mã lớp')),
                ('teacher_assigned_date', models.DateField(blank=True, null=True, verbose_name='Ngày tiếp nhận lớp')),
                ('day_of_week', models.CharField(choices=[('T2', 'Thứ 2'), ('T3', 'Thứ 3'), ('T4', 'Thứ 4'), ('T5', 'Thứ 5'), ('T6', 'Thứ 6'), ('T7', 'Thứ 7'), ('CN', 'Chủ nhật')], default='T7', max_length=2, verbose_name='Ngày học')),
                ('time_slot', models.CharField(choices=[('09h00-10h30', 'Sáng: 09h00 - 10h30'), ('10h30-12h00', 'Sáng: 10h30 - 12h00'), ('14h00-15h30', 'Chiều: 14h00 - 15h30'), ('15h30-17h00', 'Chiều: 15h30 - 17h00'), ('18h00-19h30', 'Tối: 18h00 - 19h30'), ('19h30-21h00', 'Tối: 19h30 - 21h00')], default='18h00-19h30', max_length=20, verbose_name='Ca học')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày khai giảng')),
                ('status', models.CharField(choices=[('pending', 'Sắp khai giảng'), ('active', 'Đang học'), ('completed', 'Đã kết thúc')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('completed_sessions', models.IntegerField(default=0, verbose_name='Số buổi đã học')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên phụ trách')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': '3. Quản lý Lớp học',
            },
        ),
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày dạy')),
                ('image', models.ImageField(upload_to='class_images/')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Lớp học')),
            ],
        ),
        migrations.CreateModel(
            name='ClassResignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000, verbose_name='Lý do xin rút khỏi lớp')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt (Rút khỏi lớp)'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Lớp học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Đơn xin thôi dạy',
                'verbose_name_plural': '4. Xin thôi dạy (Rút lớp)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField(verbose_name='Ngày xin nghỉ')),
                ('reason', models.TextField(max_length=500, verbose_name='Lý do nghỉ')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt (Tìm người dạy thay)'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Lớp học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Đơn xin nghỉ 1 buổi',
                'verbose_name_plural': '3. Xin nghỉ buổi (Tạm thời)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã Học viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên Học viên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('enrolled_course', models.CharField(blank=True, max_length=100, verbose_name='Môn học đăng ký')),
                ('status', models.CharField(choices=[('studying', 'Đang học'), ('reserved', 'Đang bảo lưu'), ('dropped', 'Đã nghỉ học')], default='studying', max_length=20, verbose_name='Trạng thái học')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Tổng số buổi đã mua')),
                ('remaining_sessions', models.IntegerField(default=0, verbose_name='Số buổi còn lại')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='Đã được xếp lớp')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead', verbose_name='Từ Khách hàng')),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': '2. Hồ sơ Học viên',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('studying', 'Đang học'), ('reserved', 'Đang bảo lưu'), ('dropped', 'Đã nghỉ học')], default='studying', max_length=20, verbose_name='Trạng thái')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Tổng số buổi mua cho lớp này')),
                ('sessions_consumed_before_reserve', models.IntegerField(default=0, verbose_name='Số buổi đã học (Lưu khi bảo lưu)')),
                ('reserve_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu bảo lưu')),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'verbose_name': 'Ghi danh Lớp học',
                'verbose_name_plural': 'Quản lý Ghi danh (Ví học phí)',
                'unique_together': {('student', 'enrolled_class')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', through='academic.Enrollment', to='academic.student', verbose_name='Danh sách Học viên'),
        ),
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField(blank=True, null=True, verbose_name='Mã hóa khuôn mặt')),
                ('image_reference', models.ImageField(blank=True, null=True, upload_to='face_references/', verbose_name='Ảnh mẫu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='academic.student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày dạy')),
                ('content', models.TextField(verbose_name='Nội dung bài học')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Lớp học')),
            ],
            options={
                'unique_together': {('for_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày học')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt')], default='present', max_length=25, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhận xét buổi học')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': '4. Lịch sử Điểm danh',
                'unique_together': {('student', 'for_class', 'date')},
            },
        ),
    ]
