# Generated by Django 5.2.12 on 2026-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starting_module',
            field=models.IntegerField(default=1, verbose_name='Học phần bắt đầu'),
        ),
    ]
