# Generated by Django 5.2.12 on 2026-04-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_student_starting_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_assigned',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remaining_sessions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='starting_module',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_sessions',
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('studying', 'Đang học / Chờ lớp'), ('reserved', 'Đang bảo lưu'), ('dropped', 'Đã nghỉ học')], default='studying', max_length=20, verbose_name='Trạng thái')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Tổng số buổi đã mua')),
                ('remaining_sessions', models.IntegerField(default=0, verbose_name='Số buổi còn lại')),
                ('starting_module', models.IntegerField(default=1, verbose_name='Học phần bắt đầu')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='Đã được xếp lớp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course', verbose_name='Môn học đăng ký')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Phiếu đăng ký môn',
                'verbose_name_plural': 'Phiếu đăng ký môn',
            },
        ),
    ]
