# Generated by Django 5.2.12 on 2026-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_student_enrolled_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='is_assigned',
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='status',
            field=models.CharField(choices=[('waiting', 'Chờ xếp lớp'), ('studying', 'Đang học'), ('reserved', 'Đang bảo lưu'), ('dropped', 'Đã nghỉ học')], default='waiting', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
