# Generated by Django 5.2.12 on 2026-04-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_courseregistration_is_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Tên Học viên'),
        ),
    ]
