# Generated by Django 5.2.12 on 2026-04-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_lessoncontent_actual_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='starting_module',
            field=models.IntegerField(default=1, verbose_name='Học phần Bắt đầu'),
        ),
        migrations.AddField(
            model_name='sessionabsence',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên dạy thay'),
        ),
        migrations.AlterField(
            model_name='class',
            name='completed_sessions',
            field=models.IntegerField(default=0, verbose_name='Số buổi đã học (Tổng từ HP1)'),
        ),
        migrations.AlterField(
            model_name='sessionabsence',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên xin nghỉ'),
        ),
    ]
