# Generated by Django 5.2.12 on 2026-05-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_class_starting_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(verbose_name='Ngày nghỉ')),
                ('reason', models.CharField(default='Nghỉ lễ', max_length=255, verbose_name='Lý do nghỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academic.class', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Ngày nghỉ lớp học',
                'verbose_name_plural': 'Quản lý Ngày nghỉ (Lùi lịch)',
                'unique_together': {('for_class', 'holiday_date')},
            },
        ),
    ]
