# Generated by Django 5.2.12 on 2026-04-06 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Tên Phụ huynh')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('lead_source', models.CharField(choices=[('facebook', 'Facebook Ads'), ('zalo', 'Zalo / Hotline'), ('website', 'Website Teky'), ('referral', 'Người quen giới thiệu'), ('event', 'Sự kiện / School Tour'), ('other', 'Nguồn khác')], default='facebook', max_length=20, verbose_name='Nguồn khách hàng')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Học sinh')),
                ('student_age', models.IntegerField(blank=True, null=True, verbose_name='Tuổi học sinh')),
                ('interested_course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Khóa học quan tâm')),
                ('preferred_schedule', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lịch học mong muốn')),
                ('status', models.CharField(choices=[('new', 'Mới tiếp nhận'), ('consulting', 'Đang tư vấn'), ('trial', 'Đã hẹn học thử'), ('won', 'Thành công (Đã chốt)'), ('lost', 'Thất bại (Hủy)')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú tư vấn')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Ngày hẹn gọi lại')),
                ('modules_bought', models.IntegerField(default=1, help_text='1 Học phần = 12 buổi = 5 triệu', verbose_name='Số học phần đăng ký')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm giá (%)')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='Giảm giá tiền mặt (VNĐ)')),
                ('tuition_fee', models.CharField(blank=True, max_length=50, null=True, verbose_name='Học phí thực thu (VNĐ)')),
                ('is_transferred_to_academic', models.BooleanField(default=False, verbose_name='Đã chuyển giao Học vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tư vấn viên phụ trách')),
            ],
            options={
                'verbose_name': 'Khách hàng tiềm năng',
                'verbose_name_plural': 'Danh sách Khách hàng',
            },
        ),
    ]
