# Generated by Django 5.2.12 on 2026-04-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_starting_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('facebook', 'Facebook Ads'), ('zalo', 'Zalo / Hotline'), ('website', 'Website Teky'), ('referral', 'Người quen giới thiệu'), ('event', 'Sự kiện / School Tour'), ('other', 'Nguồn khác')], default='facebook', max_length=20, verbose_name='Nguồn'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='Phụ huynh'),
        ),
    ]
